name: kitepay
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  introduction_screen: ^3.0.0
  carousel_slider: ^4.0.0
  gradient_widgets: ^0.6.0
  neopop: ^1.0.2
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor

  #state management
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0

  #data
  hive_flutter: ^1.1.0

  #Crypto
  solana: ^0.30.0

  #Firebase
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_performance: ^0.9.2+6
  firebase_core_platform_interface: ^4.8.0

  #NFC
  flutter_nfc_kit: ^3.3.1
  nfc_manager: ^3.1.1

  #utilies
  uni_links: ^0.5.1
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  qr_flutter: ^4.0.0
  pretty_qr_code: ^2.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.3
  internet_connection_checker:
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.20
  path_provider:
  share_plus: ^4.0.1
  gallery_saver: ^2.3.2
  permission_handler: ^9.2.0
  provider: ^6.0.3

dev_dependencies:
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
flutter_icons:
  android: true
  ios: true
  image_path: "assets/transparent_app_logo.png"
  adaptive_icon_foreground: "assets/transparent_app_logo.png"
  adaptive_icon_background: "#ffffff"

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: "assets/transparent_icon.png"
  color: "#1d363e"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
